// <auto-generated />
namespace MyShop2.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DataTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201911140429056_DataTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
